### PR TITLE
add requested service to use keystroke: x y z in 3rd party pkg's keymapfile

### PR DESCRIPTION
**Pull request by t9md**
Add service for requested feature #9.

@jdanbrown
I put example usage in README.md. Try!

### CODE REVIEW

**Comment by t9md** [comment]
@jdanbrown
Currently not yet published, so to try this feature you need to pull master repo directly.

After I got "it works" from you, I will publish. So give me response!

**Comment by jdanbrown** [comment]
Yep, it works! The change on my side worked exactly how you described it in your README:
- https://github.com/jdanbrown/atom-hydrogen-extras/commit/a40da61310db0ac015a1bed19d05425a688814c2

Thanks for doing that, and thanks for making it cleaner than what I started with!

**Comment by t9md** [comment]
OK! thanks for confirmation that it works.
will publish new version.

**Comment by t9md** [comment]
released v0.4.0. done!

**Pull request merged**
